// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:4926a83e-fcb3-448f-b7f6-f9ce7409fb72',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'tellmommyionic-hosting-mobilehub-668031713',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd32zyyq2ffxor4.cloudfront.net',
    'aws_mobile_analytics_app_id': '61a948d93b1b4a679e1f65fbb6fb902d',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '64a6d53e-aa61-4b37-bad0-10b416290585',
    'aws_project_name': 'tellmommy-ionic',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'tellmommyionic-mobilehub-668031713',
}

export default awsmobile;
